language: python
python:
  - "2.7"
env:
  global:
    - TRAVIS=true
  matrix:  
    - TOX_ENV=pypy-dj1.9-sqlite
    - TOX_ENV=py35-dj1.9-sqlite
    - TOX_ENV=py27-dj1.9-sqlite  
    - TOX_ENV=pypy-dj1.9-mysql
    - TOX_ENV=py35-dj1.9-mysql
    - TOX_ENV=py27-dj1.9-mysql
    - TOX_ENV=pypy-dj1.9-postgres
    - TOX_ENV=py35-dj1.9-postgres
    - TOX_ENV=py27-dj1.9-postgres  
    - TOX_ENV=pypy3-dj1.8-sqlite
    - TOX_ENV=pypy-dj1.8-sqlite
    - TOX_ENV=py35-dj1.8-sqlite
    - TOX_ENV=py27-dj1.8-sqlite  
    - TOX_ENV=pypy-dj1.7-sqlite
    - TOX_ENV=py34-dj1.7-sqlite
    - TOX_ENV=py27-dj1.7-sqlite  
    - TOX_ENV=pypy-dj1.6-sqlite
    - TOX_ENV=py33-dj1.6-sqlite
    - TOX_ENV=py26-dj1.6-sqlite
    - TOX_ENV=pypy-dj1.5-sqlite
    - TOX_ENV=py33-dj1.5-sqlite
    - TOX_ENV=py27-dj1.5-sqlite
    - TOX_ENV=py26-dj1.5-sqlite
    - TOX_ENV=pypy-dj1.4-sqlite
    - TOX_ENV=py27-dj1.4-sqlite
    - TOX_ENV=py26-dj1.4-sqlite
    - TOX_ENV=coverage
install:
  - pip install tox==2.3.1 coveralls==1.1
services:
  - mysql
  - postgresql  
addons:
  postgresql: "9.3"
script:
  - tox -e $TOX_ENV
notifications:
  email: false
branches:
  only:
    - master
after_success:
  coveralls
